[2025-05-16T23:41:27.778+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_postgres_to_duckdb.run_etl_script manual__2025-05-16T23:36:26.158794+00:00 [queued]>
[2025-05-16T23:41:27.781+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_postgres_to_duckdb.run_etl_script manual__2025-05-16T23:36:26.158794+00:00 [queued]>
[2025-05-16T23:41:27.782+0000] {taskinstance.py:2171} INFO - Starting attempt 2 of 2
[2025-05-16T23:41:27.788+0000] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): run_etl_script> on 2025-05-16 23:36:26.158794+00:00
[2025-05-16T23:41:27.790+0000] {standard_task_runner.py:60} INFO - Started process 252 to run task
[2025-05-16T23:41:27.792+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'etl_postgres_to_duckdb', 'run_etl_script', 'manual__2025-05-16T23:36:26.158794+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/etl_postgres_to_duckdb.py', '--cfg-path', '/tmp/tmpn7btc727']
[2025-05-16T23:41:27.793+0000] {standard_task_runner.py:88} INFO - Job 4: Subtask run_etl_script
[2025-05-16T23:41:27.801+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.11/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-16T23:41:27.816+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_postgres_to_duckdb.run_etl_script manual__2025-05-16T23:36:26.158794+00:00 [running]> on host 5f495f717811
[2025-05-16T23:41:27.845+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_postgres_to_duckdb' AIRFLOW_CTX_TASK_ID='run_etl_script' AIRFLOW_CTX_EXECUTION_DATE='2025-05-16T23:36:26.158794+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-16T23:36:26.158794+00:00'
[2025-05-16T23:41:27.845+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-16T23:41:27.846+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/airflow/etl/etl_postgres_to_duckdb.py']
[2025-05-16T23:41:27.849+0000] {subprocess.py:86} INFO - Output:
[2025-05-16T23:41:27.881+0000] {subprocess.py:93} INFO - Extracting data from Postgres...
[2025-05-16T23:41:27.881+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-05-16T23:41:27.881+0000] {subprocess.py:93} INFO -   File "/opt/airflow/etl/etl_postgres_to_duckdb.py", line 47, in <module>
[2025-05-16T23:41:27.881+0000] {subprocess.py:93} INFO -     data = extract_from_postgres()
[2025-05-16T23:41:27.881+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^
[2025-05-16T23:41:27.882+0000] {subprocess.py:93} INFO -   File "/opt/airflow/etl/etl_postgres_to_duckdb.py", line 16, in extract_from_postgres
[2025-05-16T23:41:27.882+0000] {subprocess.py:93} INFO -     conn = psycopg2.connect(
[2025-05-16T23:41:27.882+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^
[2025-05-16T23:41:27.882+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
[2025-05-16T23:41:27.882+0000] {subprocess.py:93} INFO -     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
[2025-05-16T23:41:27.882+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-05-16T23:41:27.882+0000] {subprocess.py:93} INFO - psycopg2.OperationalError: connection to server at "localhost" (::1), port 5432 failed: Connection refused
[2025-05-16T23:41:27.882+0000] {subprocess.py:93} INFO - 	Is the server running on that host and accepting TCP/IP connections?
[2025-05-16T23:41:27.882+0000] {subprocess.py:93} INFO - connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
[2025-05-16T23:41:27.882+0000] {subprocess.py:93} INFO - 	Is the server running on that host and accepting TCP/IP connections?
[2025-05-16T23:41:27.882+0000] {subprocess.py:93} INFO - 
[2025-05-16T23:41:27.886+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-16T23:41:27.891+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-16T23:41:27.893+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=etl_postgres_to_duckdb, task_id=run_etl_script, execution_date=20250516T233626, start_date=20250516T234127, end_date=20250516T234127
[2025-05-16T23:41:27.897+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 4 for task run_etl_script (Bash command failed. The command returned a non-zero exit code 1.; 252)
[2025-05-16T23:41:27.929+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-16T23:41:27.937+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
